apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: "119.81.106.194"
  apiServerPort: 58443
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker