  version: '3.8'
  services:
    jenkins:
      image: jenkins/jenkins:lts
      container_name: jenkins
      privileged: true
      user: root
      volumes:
        - ./:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - "8080:8080"
        - "50000:50000"